upstream event_sync_service {
    server unix:/run/event-sync/gunicorn.sock fail_timeout=0;
}

server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/event_sync_access.log;
    error_log /var/log/nginx/event_sync_error.log;

    client_max_body_size 1M;

    location / {
        proxy_pass http://event_sync_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;
        proxy_read_timeout 30s;
        proxy_connect_timeout 5s;
        proxy_send_timeout 10s;
    }
}
